# Generated by Django 6.1 on 2026-09-04 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='catrgory',
            new_name='catergory',
        ),
    ]
