# Generated by Django 6.1 on 2026-09-04 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='catergory',
            new_name='category',
        ),
    ]
